### ISSUE TITLE
Implement version markup

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem2#10]
- remove svnversion from Makefile and atchem.f
- delete svn_version.f

Question:  is a version markup needed? if so can we swap the svn generated code with a git generated code?

**Comment by spco** [comment]
I'm currently pondering this one - a version markup can be useful, especially when it comes to reproducibility of results. However, it's impossible to hardcode the git commit hash into the commit, as the hash is a function of the contents of the commit! So I'm not sure what to replace this with.

For now, I've ripped it out and not replaced it. We can come back to this later on once the dust settles.

**Comment by rs028** [comment]
Agreed. It would be useful, but can wait.
Maybe a date stamp could be easier to implement/more meaningful than a version number?

**Comment by spco** [comment]
Note: svn printing mechanism was removed in 421f5f101.

**Comment by rs028** [comment]
@spco this may be relevant: https://help.github.com/articles/about-releases/

**Comment by spco** [comment]
Yes, I'm definitely planning to make use of that functionality. I'm still not sure how to add in a more accurate version number than just hard-coding the latest major or minor release.

**Comment by rs028** [comment]
Okay. It's low priority anyways

**Comment by spco** [comment]
Closed by #293. We must just remember to update this each time we release a new version, or start dev work on the next.
