### ISSUE TITLE
Use cmd-line parser

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem2#121]
We should definitely replace the current command-line interface (which is incredibly rough, and not fit for purpose, it's just the easiest to hack together) with the Fortran Command Line Arguments Parser https://github.com/szaghi/FLAP.

**Comment by rs028** [comment]
I like this. It can be tied to a more sensible organization of the directories. Right now, some things are in shared directories (src/, tools/) and others in model-specific directories. I think a more structured approach would siumplify the compilation and running of the model (hence a simpler command line interface).

**Comment by spco** [comment]
Agreed. Are you thinking something along the lines of `obj/`, `src/`, `tools/`, `travis/` and `model/` (new) as high-level directories, with `environmentConstraints/`, `instantaneousRates/`, `modelConfiguration/`, `speciesConstraints/`, and maybe `modelOutput/` moved inside `model/`?

Along with the cmd-line parser and function parser, I think that this would really make the structure of the code more organised and functional, close to where we want it to be. The structure should be almost self-explanatory to the user, so grouping things like that would be a good step, definitely.

**Comment by spco** [comment]
And while I think of it, the contents of `tools/` should probably be organised as well. There are a number of scripts in there, and it's not immediately obvious what they all do. Some might want renaming to be more descriptive. Lots to think about!

**Comment by rs028** [comment]
Yes that's exactly what I mean. I am not sure what is the best (and best practice) approach, but something along the lines of what you suggest.

**Comment by spco** [comment]
See https://github.com/AtChem/AtChem2/pull/370#issuecomment-452776986 for further discussion of what might be a sensible balance between flexibility and simplicity of the interface.

**Comment by spco** [comment]
Closed by #378
