### ISSUE TITLE
calculation of DEC is likely wrong. Check that SZA is correct.

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem2#14]
The calculation of the sun declination (DEC) is likely wrong. It should be:
- at summer solstice = +0.41 rad
- winter solstice = -0.41 rad
- spring and autumn equinoxes = 0 rad

It may be related to longitude east being positive rather then negative. This needs to be tested on a range of dates and latitudes/longitudes.

**Comment by rs028** [comment]
Sun declination is not related to latitude/longitude but is a function of time only. The equation in calcDec (constraintFunctions.f90) is off by about 11 days. Need to fix this and check that the SZA is calculated correctly (in zenith.f90)

**Comment by spco** [comment]
I'm currently working on a PR to fix the calculation of dec, using the equation from https://en.wikipedia.org/wiki/Position_of_the_Sun#Declination_of_the_Sun_as_seen_from_Earth

**Comment by rs028** [comment]
I was going to do that, but I haven't started yet, so if you prefer to do it yourself, I can focus on the test scenarios.

PS: there a couple different ways to do that. The function fSolar in https://github.com/rs028/atmosch-R/blob/master/atmosPhys.R also does that with a different approach. In principle they should give the same (or at least very similar) numbers, so it can be used to double check the results. Sound reasonable?

**Comment by spco** [comment]
#112 fixes the calculation of DEC with a more accurate version. SZA has not been checked.

**Comment by rs028** [comment]
@spco Can you assign this to me?

**Comment by rs028** [comment]
@spco, I am finally getting to the bottom of this. 
Both the old and the new equations for DEC are wrong (I think the one you used is for astronomy, which is a slightly different calculation). Should I wait until we have merged PR #206 and #208 or can I just branch off the present master? I don't want to do a messy reconciliation.

**Comment by spco** [comment]
Feel free to make a change to the DEC calculation straight off the latest master - perhaps a better version of that will solve my numerical issues! I can handle the messy reconciliation later, just keep the PR very focused on that one change (plus resultant changes to output files).

**Comment by rs028** [comment]
Okay. do you want to merge #206 now? It is not complete, but it is all set up to make it easy to add comments and descriptions. Since it is a lot of files, may be easier to it now.

**Comment by spco** [comment]
I need to get my train, and there are currently conflicts with the master branch - are you ok if I do this first thing tomorrow? The PR looks fine, but the conflicts need handling, and I don't have the few minutes right now! Feel free to just branch now and rebase later, if you're comfortable doing that.

**Comment by rs028** [comment]
Yeah, no worries.

**Comment by rs028** [comment]
I am reopening this issue, because the calculation of the Local Hour Angle (and therefore DEC, SZA) is wrong.
