### ISSUE TITLE
Give timeline of development on wiki

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem2#228]
I think it would be useful to alter the Acknowledgements and Credits wiki page to reflect the history of development, showing the rough years that researchers have worked on the code, and a one-line summary of their contributions. That would help users see (a) who did what, and more importantly (b) who to contact about the current code. @rs028 Would you be able to do this?

I'm thinking something like
```
University of Leeds - first version, implementation of... 

    Kasia Borońska (2005-2010)
    Peter Jimack (2007-2012) etc.
    Chris Martin
    Mike Pilling
    David Waller
    Jenny Young

University of York / NCAS

    Andrew Rickard

CEAM

    Monica Vázquez Moreno

University of Leicester - complete rewrite of code base to modern Fortran standards, test suite, version control.

    Sam Cox (2017-)
    Roberto Sommariva (also at University of Birmingham) (2017-)
```

**Comment by rs028** [comment]
Good idea. Will do it. If you need to specifacally mentione ReSet feel free to add it.

**Comment by rs028** [comment]
@spco When you have time can you have a look at the Acknowledgements page on the wiki to check that you are happy with it.  Then this can also be closed.
