### ISSUE TITLE
Release a version!

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem2#247]
When we're happy, tag a commit as v1! 😄

**Comment by rs028** [comment]
Cool :)
So are we going for AtChem2 as a name or do you have a better suggestion?

**Comment by spco** [comment]
I don't mind! If we come back to this in 6 months' time and stick in the function parser, what would then then call it? AtChem3, or Atchem2 version 2? 😆

**Comment by rs028** [comment]
AtChem2 v1.0
AtChem2 v1.1
AtChem2 v2.0

Not very imaginative. I need to think about that but I am open to suggestions.

**Comment by spco** [comment]
@rs028 - if you agree that we're ready, would you like to do the honours?

**Comment by rs028** [comment]
All right. I think it is done! 🍾
