### ISSUE TITLE
Can't build/install AtChem2

### ISSUE THREAD

**Issue by NikosAlexandris** [AtChem/AtChem2#254]
After installing all dependencies, I can't `make` it!

The error(s):
```
./tools/build.sh ./tools/mcm_example.fac

input mechanism file: ./tools/mcm_example.fac
fortran output directory:
mechanism output directory:

call setup_atchem2.py
/home/nik/code/AtChem2/tools
Running fix_fac_file on /home/nik/code/AtChem2/tools/mcm_example.fac
/home/nik/code/AtChem2/tools/mcm_example.fac: file read in 520 items
0 corrections made - now removing old
Reading input file
looping over inputted ro2s
adding RO2 to src/ro2-rates.f90

make ./tools/mcm_example.fac
touch makefile.$(uname -n | perl -pe 's/\..+//')
ln -f makefile.$(uname -n | perl -pe 's/\..+//') makefile.local
gfortran -o atchem2 -Jobj -Iobj src/dataStructures.f90 src/interpolationFunctions.f90 src/configFunctions.f90 src/inputFunctions.f90 src/outputFunctions.f90 src/atmosphereFunctions.f90 src/solarFunctions.f90 src/constraintFunctions.f90 src/solverFunctions.f90 src/parameterModules.f90 src/atchem2.f90 -ffree-form -fimplicit-none -Wall -Wpedantic -fcheck=all -L/home/nik/code/AtChem2/libraries/cvode/ -L/usr/lib64/ -Wl,-R,/usr/lib/:/usr/lib64/blas/lib:/usr/lib64/lapack/lib:/home/nik/code/AtChem2/libraries/cvode/:/usr/lib64/:/usr/lib64/ -lopenlibm -lsundials_fcvode -lsundials_cvode -lsundials_fnvecserial -lsundials_nvecserial -lblas -llapack
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lsundials_fcvode
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lsundials_cvode
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lsundials_fnvecserial
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lsundials_nvecserial
collect2: error: ld returned 1 exit status
Makefile:82: recipe for target 'atchem2' failed
make: *** [atchem2] Error 1
```

Both `openlibm` and the (optional) `numdiff` are installed from the system's available packages. For `CVODE`, though, I opted the one that the script `install_cvode.sh` installs. I run Funtoo-Linux. I think that I have set correctly the paths in the `makefile.$(hostname)`:
```
BLASDIR=/usr/lib64/blas/lib
LAPACKDIR=/usr/lib64/lapack/lib
CVODELIB=/home/nik/code/AtChem2/libraries/cvode/
OPENLIBMDIR=/usr/lib64/
LIBDIR=/usr/lib/:$(BLASDIR):$(LAPACKDIR):$(CVODELIB):$(OPENLIBMDIR)
```

I've repeated all by using, in addition, the install scripts for `openlibm` and `numdiff` (and removed the local installed stuff).

I face the same errors.  Perhaps I need to check the $PATH.

In any case, I think it's a bit hard to get it done if one has no Linux and source compilation skills.  This way is only for experienced users.

Couldn't you pre-cook stuff and dockerize the whole thing?

**Comment by rs028** [comment]
I think your paths are wrong. They should be:

    /home/nik/code/AtChem2/libraries/cvode/lib
    /usr/lib64/openlibm-0.4.1/

that is where the `*.so` files are.

**Comment by NikosAlexandris** [comment]
Thanks. Indeed for CVODE. But `openlibm` is not placed under `lib64` in Gentoo/Funtoo. Anyway, I installed it (again) via "your" install script. The make file

```
BLASDIR=/usr/lib64/blas/lib
LAPACKDIR=/usr/lib64/lapack/lib
CVODELIB=/home/nik/code/AtChem2/libraries/cvode/lib/
OPENLIBMDIR=/home/nik/code/AtChem2/libraries/openlibm-0.4.1/
LIBDIR=/usr/lib/:$(BLASDIR):$(LAPACKDIR):$(CVODELIB):$(OPENLIBMDIR)
```

and the error(s):
```
./tools/build.sh ./tools/mcm_example.fac

input mechanism file: ./tools/mcm_example.fac
fortran output directory:
mechanism output directory:

call setup_atchem2.py
/home/nik/code/AtChem2/tools
Running fix_fac_file on /home/nik/code/AtChem2/tools/mcm_example.fac
/home/nik/code/AtChem2/tools/mcm_example.fac: file read in 520 items
0 corrections made - now removing old
Reading input file
looping over inputted ro2s
adding RO2 to src/ro2-rates.f90

make ./tools/mcm_example.fac
touch makefile.$(uname -n | perl -pe 's/\..+//')
ln -f makefile.$(uname -n | perl -pe 's/\..+//') makefile.local
gfortran -o atchem2 -Jobj -Iobj src/dataStructures.f90 src/interpolationFunctions.f90 src/configFunctions.f90 src/inputFunctions.f90 src/outputFunctions.f90 src/atmosphereFunctions.f90 src/solarFunctions.f90 src/constraintFunctions.f90 src/solverFunctions.f90 src/parameterModules.f90 src/atchem2.f90 -ffree-form -fimplicit-none -Wall -Wpedantic -fcheck=all -L/home/nik/code/AtChem2/libraries/cvode/lib/ -L/home/nik/code/AtChem2/libraries/openlibm-0.4.1/ -Wl,-R,/usr/lib/:/usr/lib64/blas/lib:/usr/lib64/lapack/lib:/home/nik/code/AtChem2/libraries/cvode/lib/:/home/nik/code/AtChem2/libraries/openlibm-0.4.1/:/home/nik/code/AtChem2/libraries/openlibm-0.4.1/ -lopenlibm -lsundials_fcvode -lsundials_cvode -lsundials_fnvecserial -lsundials_nvecserial -lblas -llapack
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lsundials_fcvode
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lsundials_cvode
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lsundials_fnvecserial
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lsundials_nvecserial
collect2: error: ld returned 1 exit status
Makefile:82: recipe for target 'atchem2' failed
make: *** [atchem2] Error 1
```

**Comment by spco** [comment]
Hi @NikosAlexandris, thanks for the feedback. The build system has been tested on a limited number of setups, so there may be teething problems with those we haven't seen yet.

1) Can you confirm that the correct CVODE libraries exist in the correct location, e.g. `/home/nik/code/AtChem2/libraries/cvode/lib/libsundials_cvode.so`.

2) If it does exist, can you post the output of the command `ldd libsundials_cvode.so` from that directory?

3) And finally, can you confirm where Gentoo/Funtoo does install openlibm, either via the install script or as a system-installed package?

**Comment by rs028** [comment]
Also make sure you are editing `makefile.<hostname>` not `makefile.local`, which is overwritten every time you run the build script. On our supercomputer I need to  have a different `makefile.<hostname>` for each login node (although the content is the same).

**Comment by NikosAlexandris** [comment]
A typo in both entries in the "make" file! Instead of
```
CVODELIB=/home/nik/code/AtChem2/libraries/cvode/lib/
OPENLIBMDIR=/home/nik/code/AtChem2/libraries/openlibm-0.4.1/
```
the correct path
```
CVODELIB=/home/nik/code/AtChem2/**librairies**/cvode/lib/
OPENLIBMDIR=/home/nik/code/AtChem2/**librairies**/openlibm-0.4.1/
```
leads to a successful compilation.

Thanks.

Answering to @spco,
1. It was a typo
2. ```ldd libsundials_cvode.so
        linux-vdso.so.1 (0x00007fff3edfd000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f73906e7000)
        /lib64/ld-linux-x86-64.so.2 (0x000055f192836000)```
3. the install script installs, as expected, wherever it is instructed to do so -- in this case, inside `/home/nik/code/AtChem2/librairies/openlibm-0.4.1`.  As for Gentoo/Funtoo, at the moment I have to deal with something else and I can't tell.  Expectedly, though, it should be in some of the /usr/lib* directories.

**Comment by spco** [comment]
I'm glad you found your typo! Thanks for the extra info, looks like you are all set up 👍

**Comment by rs028** [comment]
Good. Thanks for taking the time to check the installation procedure and give us feedback.
