### ISSUE TITLE
Photolysis Rates questions

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem2#258]
Unclear from the documentation and other outstanding questions:

- [ ] Are photolysis rates set to zero (or to some extremely low value) at night?
- [x] Can ROOFOPEN environment variable be constrained? 
- [ ] The online version used to have the option to set a constant photolysis rates (see https://github.com/AtChem/AtChem2/wiki/2.5-Photolysis-Rates-and-JFAC#constant-photolysis-rates). Does it still work or was it removed with the "online bits"?
- [x] The output in `photolysisRates.output` sometimes still contains the mistake in the format when the exponent is 3 digits. e.g.: 1e-100 is written as 1-100. **NOTE:** this can also happen in the other output files.

**Comment by spco** [comment]
Yes, #277 resolves this fully (as far as I can see)

**Comment by rs028** [comment]
I close this, as the remaining issues are now being addressed in #272 and #276.
