### ISSUE TITLE
Use different setup for documentation

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem2#260]
We should explore the use of a github.io or gitbook.com setup for documentation, as these may be more accessible/configurable than the GitHub wiki pages.

**Comment by rs028** [comment]
Alternative: readthedocs.org

A different solution is to use a `*.tex` file in a `doc/` folder

**Comment by rs028** [comment]
PR #373 partially solves this. Need to convert the `*.md` files to `*.tex`.
Note: use **pandoc**?

**Comment by spco** [comment]
Closed by #385
