### ISSUE TITLE
Model compilation successful but cannot run the excutable

### ISSUE THREAD

**Issue by ShuxuanXu** [AtChem/AtChem2#261]
Hello

I followed the instruction to install all dependencies (the path is <code>/Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/atchem_lib</code>) and created the <code>makefile.hostname</code> script. Then I tried to run <code>./tools/build.sh ./tools/setup_atchem2.py</code>.The compiling message is below:

> input mechanism file: ./tools/mcm_example.fac
> fortran output directory:
> mechanism output directory:
> 
> call setup_atchem2.py
> /Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/tools
> Running fix_fac_file on /Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/tools/mcm_example.fac
> /Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/tools/mcm_example.fac: file read in 520 items
> 0 corrections made - now removing old
> Reading input file
> looping over inputted ro2s
> adding RO2 to src/ro2-rates.f90
> 
> make ./tools/mcm_example.fac
> touch makefile.$(uname -n | perl -pe 's/\..+//')
> ln -f makefile.$(uname -n | perl -pe 's/\..+//') makefile.local
> gfortran -o atchem2 -Jobj -Iobj src/dataStructures.f90 src/interpolationFunctions.f90 src/configFunctions.f90 src/inputFunctions.f90 src/outputFunctions.f90 src/atmosphereFunctions.f90 src/solarFunctions.f90 src/constraintFunctions.f90 src/solverFunctions.f90 src/parameterModules.f90 src/atchem2.f90 -ffree-form -fimplicit-none -Wall -Wpedantic -fcheck=all -L/Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/atchem_lib/cvode/lib/ -L/Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/atchem_lib/openlibm-0.4.1/ -Wl,-rpath,/usr/lib/:/usr/lib/libblas.dylib:/usr/lib/liblapack.dylib:/Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/atchem_lib/cvode/lib/:/Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/atchem_lib/openlibm-0.4.1/:/Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/atchem_lib/openlibm-0.4.1/ -lopenlibm -lsundials_fcvode -lsundials_cvode -lsundials_fnvecserial -lsundials_nvecserial -lblas -llapack

I am not sure, but it looks good (no error messages displayed). And the excutable <code>atchem2</code> did show up in the directory. When I ran <code>./atchem2</code>, the error message is like:

> dyld: Library not loaded: @rpath/libsundials_cvode.2.dylib
>   Referenced from: /Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/./atchem2
>   Reason: image not found
> Abort trap: 6

It seems that the excutable didn't find the cvode/lib directory.

Then, I tried <code>otool -L ./atchem2</code>. The message is:
>(...)
>           cmd LC_LOAD_DYLIB
>       cmdsize 64
>          name @rpath/libsundials_cvode.2.dylib (offset 24)
>    time stamp 2 Thu Jan  1 01:00:02 1970
>       current version 2.9.0
> compatibility version 2.0.0
> Load command 14
>           cmd LC_LOAD_DYLIB
>       cmdsize 64
>          name @rpath/libsundials_fnvecserial.2.dylib (offset 24)
>    time stamp 2 Thu Jan  1 01:00:02 1970
>       current version 2.7.0
> compatibility version 2.0.0
> Load command 15
>           cmd LC_LOAD_DYLIB
>       cmdsize 64
>          name @rpath/libsundials_nvecserial.2.dylib (offset 24)
>    time stamp 2 Thu Jan  1 01:00:02 1970
>       current version 2.7.0
> compatibility version 2.0.0
> Load command 16
>(...)

and the rpath is:

>           cmd LC_RPATH
>       cmdsize 320
>          path /usr/lib/:/usr/lib/libblas.dylib:/usr/lib/liblapack.dylib:/Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/atchem_lib/cvode/lib/:/Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/atchem_lib/openlibm-0.4.1/:/Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/atchem_lib/openlibm-0.4.1/ (offset 12)
> 

my cvode/lib looks like:

> libsundials_cvode.2.9.0.dylib       libsundials_fnvecserial.a
> libsundials_cvode.2.dylib           libsundials_fnvecserial.dylib
> libsundials_cvode.a                 libsundials_nvecserial.2.7.0.dylib
> libsundials_cvode.dylib             libsundials_nvecserial.2.dylib
> libsundials_fcvode.a                libsundials_nvecserial.a
> libsundials_fnvecserial.2.7.0.dylib libsundials_nvecserial.dylib
> libsundials_fnvecserial.2.dylib
> 

my macOS version: High Sierra 10.13.2

**Comment by spco** [comment]
HI @ShuxuanXu,
> dyld: Library not loaded: .2.dylib

looks very suspicious to me. Can I ask for the contents of `makefile.hostname`, and what the `hostname` is?

Could you also run 
`gfortran --version`
`gcc --version`
and
`pkgutil --pkg-info=com.apple.pkg.CLTools_Executables` and post the output?

Thanks for using the package - we're always keen to try out on different machine setups, so your feedback is useful.

**Comment by spco** [comment]
> Then I tried to run ./tools/build.sh ./tools/setup_atchem2.py.The compiling message is below:

Can I clarify that above you meant to type:
Then I tried to run `./tools/build.sh ./tools/mcm_example.fac` . ?

**Comment by ShuxuanXu** [comment]
Oh sorry about that. I did type <code>./tools/build.sh ./tools/mcm_example.fac</code>, not the incorrect one I said above.

This is the version info:
<img width="914" alt="screen shot 2018-01-15 at 17 30 08" src="https://user-images.githubusercontent.com/12758417/34954820-c4128420-fa19-11e7-94bd-190bd45a7658.png">

<code>makefile.hostname</code> is:

<code></code>
<code></code>

**Comment by ShuxuanXu** [comment]
the hostname is "Shuxuans-MacBook-Pro"

**Comment by spco** [comment]
Hmm, this will need further exploration. Have you altered line 41 in `Makefile` to point to your cvode library directory?

After that check, I'll need to see more of what you're doing. Could you do a clean install of both CVODE and AtChem? Before calling `./tools/build.sh`, please alter the final line of `Makefile` to read `make V=1 --always-make` and then send me the full output of all those steps (copy and paste from Terminal). Thanks.

**Comment by spco** [comment]
Hi @ShuxuanXu, just in case you haven't yet started the reinstall, please don't start - I've realised that the code above isn't showing correctly, and I know the reason! (TBC)

**Comment by spco** [comment]
I hadn't realised that the quoted code above wasn't showing correctly - the use of quotes (> syntax) has garbled the `@rpath/libsundials_cvode.2.dylib` syntax, assuming `@rpath/libsundials_fnvecserial` is a GitHub username, and ignoring it as it can't find that repository.

The correct error output is:
```
dyld: Library not loaded: @rpath/libsundials_cvode.2.dylib
Referenced from: /Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/./atchem2
Reason: image not found
Abort trap: 6
```

This I do know how to fix! We can do it in 2 ways:

**Easy way:**
`export DYLD_LIBRARY_PATH=/Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/atchem_lib/cvode/lib`

**Longer but 'cleaner' way:**
Run
`otool -change @rpath/libsundials_cvode.2.dylib /Users/shuxuan/code/kinetic_chamber_modelling_xsx/AtChem2/atchem_lib/cvode/lib/libsundials_cvode.2.dylib atchem2`

Then try `./atchem2` again. This should give you a similar message about `libsundials_fnvecserial.2.dylib`. Fix that similarly, and again for `libsundials_vecserial.2.dylib`.

Either of these should fix the problem. If using the easy way, remember to set this variable every time you open a new Terminal window, or alternatively set it in your `~/.bash_profile`.

See https://stackoverflow.com/questions/17703510/dyld-library-not-loaded-reason-image-not-loaded for a good discussion of the two methods.

Hopefully that solves you issues - could you confirm whether it does or doesn't? Thanks!

**Comment by ShuxuanXu** [comment]
Sorry about that (a little weird) mistake.
This perfectly solved the problem. Thank you so much!

**Comment by spco** [comment]
Great to hear. I will close this issue.

Thanks for using AtChem2, and please send us any issues and fixes or ideas!
