### ISSUE TITLE
Plotting tools

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem2#269]
Python script:
- ~import too many libraries?~
- generally slow
- ~inefficient way to read file header and data (open file twice)~
- ~spacing between panels~

gnuplot script:
- ~does not read variable names from file header~
- ~unequal dimension of panels~
- ~spacing between panels~

Matlab/Octave script:
- ~inefficient way to read file header and data (open file twice)~
- ~does not save to pdf~

**Comment by rs028** [comment]
Python version fixed by PR #394, but still slow. The version with pandas is only marginally quicker than the version with numpy. (keep both?)

**Comment by spco** [comment]
For reference, it's not the data processing that's really expensive - it's the many calls to `savefig()` and `tight_layout()` that do the damage, as seen in this flame graph (this is for the case I'm investigating in #384). `save_fig()` is taking 0.7s per PDF page (of which there are 12 = 8.4s), while `tight_layout()` is taking 0.192s per graph (there are 62 of these = 11.9s) :
![Screenshot 2019-05-21 at 14 00 15](https://user-images.githubusercontent.com/11610738/58098221-fbd58800-7bd0-11e9-956e-991a488affbb.png)
