### ISSUE TITLE
Simplify photolysis rates read

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem2#272]
The reading in of photolysis rate is a bit of a mess currently:
```
readPhotoRates()
 `-> readPhotolysisConstants()
      `-> readPhotolysisRates()
```
is a nightmare structure for knowing which calls which, and this is the only time they're called. At the least, these need renaming, but I think it would be better to combine that with a rethink of the structure - these shouldn't really be nested.  Better to simplify the logic of the whole thing.

**Comment by spco** [comment]
The fix in #273 adds a slight annoyance in that the filename of `photolysisConstants.config` is used in two places. This should be neatened up before this issue is closed.

**Comment by spco** [comment]
@rs028 A couple of questions on this (not urgent to answer): I think the current logic is that there are two types of photolysis possible at any one time: we have either (a) some rates are fixed constants (from `photolysisConstants.config`), and some are (varying with time) constrained (`constrainedPhotoRates.config`) ; or (b) some rates are calculated (`constrainedPhotoRates.config`), and some are (varying with time) constrained (`photolysisRates.config`). 
`nrOfPhotoRates` hold how many are either constant or calculated, and `numConPhotoRates` how many are constrained.

(1) It's possible to supply the same species in both constant and constrained, or calculated and constrained. In this case, the calculated or constant gets overwritten by the constrained. I guess to be a bit more efficient we could check whether there's any overlap, and remove the overlapping ones from the calculated or constant group - the constrained rate will always be applied anyway, so why waste time calculating? What do you think? And is this the right order of prioritisation, or should e.g. the calculated rate always trump the others?

(2) Do we want this to be exclusive (only constants or calculated allowed, never a mix) or would it be useful to have some calculated and others fixed constants? At present that can be 'hacked' by supplying a constant value in the constraints file, but I think supplying both a constants and a rates file should be allowed, as well as the constraints file. Thoughts?

**Comment by rs028** [comment]
@spco I haven't really looked at how the photolysis rates are implemented so I cannot comment on everything. That being said this is how I think it should work.

case 1: all photolysis rates are calculated. Using the info in `photolysisRates.config` and the MCM parametrization (see http://mcm.leeds.ac.uk/MCMv3.3.1/parameters/photolysis_param.htt)

case 2: all photolysis rates are constrained.

case 3: some photolysis rates are constrained, those that are not constrained are calculated.

case 4: all photolysis rates are zero. This can be done currently either by setting `ROOFOPEN` to OFF or by setting `JFAC` to 0.

case 5: some or all photolysis rates are constants. This does not make sense for an ambient simulation so it is meant for chamber simulations only (it basically means there is a lamp). In this case if not all rates are set to a constant, the others should be zero (the logic being that the lamp only uses certain wavelengths). I am not sure if this works, as there is no `photolysisConstants.config` in model Configuration. See also issue #258 and the wiki page (https://github.com/AtChem/AtChem2/wiki/2.5-Photolysis-Rates-and-JFAC), which probably will need rewriting.

On top of all of this, there is the issue of JFAC which should scale only the calculated rates not the constrained or constant ones.

So I guess the answer to your questions is that this is a mighty mess :)

**Comment by spco** [comment]
That's fine - one to discuss when we get to it! I'm just filling a bit of spare time waiting for input on other projects with a look at the numerics of AtChem, so I'm finding bits and bobs to fix as I go :)

**Comment by spco** [comment]
Oh, and I think the constant photolysis case should work (most of the logic is in there), but you're right that we don't seem to have any tests for this. That should be tested and investigated. Having some rates constant will be cheaper than the hack of giving them constant values to be interpolated as constrained data.

As another point in this whole thing, it would be nice if rather than having the file `modelConfiguration/constrainedPhotoRates.config`, which just contains a list of the names of the photo rates to constrain, and then having a file for each of those in `environmentConstraints`, we could instead just rely on looking in that directory, seeing what files exist, and constraining those. It's a bit clunky to have a file that just lists what other files exist, and which may or may not be up-to-date with the actual contents of the directory. It requires updating that file every time you add a new constraints file.
That said, some googling shows that that's not really possible with portable Fortran, as it can't ask the filesystem for all the files in a directory.
As a possible help, we could provide a script that auto-generates the list of files in the directory. You'd then just need to run that before running AtChem. It wouldn't be required (you can curate that list by hand as now), but might be useful. Then in a qsub script you'd just run that line before calling AtChem?

**Comment by rs028** [comment]
This actually applies to `constrainedFixedSpecies.config` (which is also not being tested at the moment) and `constrainedSpecies.config`, as well.

I am undecided if it would be a good thing to do it automatically. My typical workflow consists in producing all the constraint files for a given project and then change the configuration files for each run to tell the model which ones must be used. However it is not necessarily the most efficient way.

One solution could be to use a configuration file like `environmentVariables.config` for the photolysis rates, telling the model which ones need to be constraned and which ones calculated.

This issue is also related to #17 . What if I add manually a new reaction that is not in the MCM and I want its photolysis rate (eg, J70) to be constrained?

**Comment by spco** [comment]
@rs028 Ok, so here's what I think we want for handling photolysis rates, based on what you've said above.

![photolysisratesflowdiagram](https://user-images.githubusercontent.com/11610738/41652166-3e1956d8-747a-11e8-867f-cafd444bfcc6.png)

I imagine this being done once at the beginning, essentially as an expanded `readPhotoRates()`. We can then use `PR_type` during execution to decide whether we need to even generate the arrays for constrained photo rates, for example, or whether we need to calculate `JFAC` or do integration at points.

Does this match up with what you'd want to be able to do? We would want to check (which already happens) that all the constraint files exist if they're needed. 

The part that worries me currently is, what is the best mechanism for setting all photo rates to zero, in the first decision? Currently, setting `ROOFOPEN=OFF` sets only calculated photo rates to zero - constrained and constant values are unaffected. Setting `JFAC=0` by hand in `environmentVariables.config` similarly only affects calculated photo rates. It seems you want to be able to set ALL photo rates to zero.

I guess if you have nothing in `photolysisConstants.config` and `constrainedPhotolysisRates.config` then all PRs will be calculated, so the zero JFAC would be applied to all. Perhaps this is the best way to do things - force the user to remove all from those two files, so that they're not confused when some 'set all PRs to zero' setting gets applied and overrules those files. It is a consistent method,

If that's the way you think is best to have it, then we can do a check at the beginning - if JFAC is zero and all PRs are to be calculated, then we set 'PR_type = 0' as in the diagram above, and that saves us calculating all the photolysis rates each time we evaluate `mechanism_rates()` (a lot of times!).

**Comment by rs028** [comment]
That is correct. Two things:

- `PR_type = 3` JFAC **can** be calculated **or** provided by the user, either as constraint or as a constant value.
- `PR_type = 4` JFAC **must** be provided by the user, either as constraint or as a constant value.

I don't think we need `PR_type = 0` for the following reasons:

`JFAC` and `ROOFOPEN` have two different uses.
- `JFAC` is meant to scale the calculated PR in ambient conditions. This accounts for example for the presence of clouds. Setting JFAC to zero has the effect of setting all calculated (but not constrained) PR to zero. This is sort of an unintended consequence.
- `ROOFOPEN` is meant for environmental chambers that can shut their roof to stop solar light (think this http://www.ceam.es/WWWEUPHORE/home.htm). Setting `ROOFOPEN` to `OFF` should therefore set all PR to zero, except for those that are constrained or constant (which means that inside the dark chamber there is a lamp).

This means that the only way "legal" way to set all photolysis rates to zero should be to use `photolysisConstants.config` (or to create a bunch of constraint files with zero in them). If there are no constants and no constraints, one can obtain the same effect using `ROOFOPEN` or `JFAC`. It will work but that's not what they are for.

**Comment by spco** [comment]
As a correction to the above, because having anything in `photolysisConstants.config` sets all other PRs to 0 (see `PR_type = 1` case), we can all PRs to 0 by naming just one of them in `photolysisConstants.config` with zero value.

**Comment by spco** [comment]
![photolysisratesflowdiagram2](https://user-images.githubusercontent.com/11610738/41661410-9ca64b68-7496-11e8-91d2-ccaf37007d65.png)

**Comment by spco** [comment]
If we're happy with that flow, I can get that sorted out as it shouldn't rely on any other parts?

**Comment by rs028** [comment]
Okay looks good. For the moment I would leave JFAC calculation out and just force the user to provide it. The current way to calculate it is crude and does not always work (see #16). But I need to think what is the best way to calculate it.

**Comment by spco** [comment]
@rs028, is it safe to force the user to provide the basic `photolysisRates.config` at all times, even if they're not used? It's part of the MCM, so I imagine so, but I want to check.

The reason I ask is that, if supplied with a `photolysisConstants.config` with just a single line defining a single photolysis rate, I need to know what all the possible photolysis rates are that will come up later in the calculation. E.g. `photolysisConstants.config` just contains `J3`, but the `.fac` contains references to `J5`, `J6`, etc. Rather than checking whether these exist when it comes to all the calculations, I'd rather have an array setting them all to zero explicitly - I can then look up in the array. Much faster.

So can I assume that `photolysisRates.config` is always provided, and that it contains all the photolysis rates that the `.fac` will reference? I note that e.g. `J9`, `J10`, `J20` and a few others aren't present in `photolysisRates.config`. Is it safe to assume that they won't ever appear in the `.fac`, and if they do appear, to default to zero value? Or should it error out?

**Comment by spco** [comment]
I think the only sensible way to do this is to assume that `photolysisRates.config` is provided, and that `photolysisConstants.config` cannot supply a a J-number greater than the max in `photolysisRates.config`. This is reasonable, and being unable to assume that really scuppers being able to do anything without a major rehaul.

**Comment by rs028** [comment]
I think `photolysisRates.config` is similar to `RO2List` in the sense that it is tied to a specific version of the MCM. The easiest way - though maybe not ideal - is to just provide it with AtChem.

About the `J` array size I have been using the missing values to add photolysis rates. For example add a constrained photolysis rate for a reaction that is not in the MCM and call it `J9`. It is a bit of dirty hack, but do you think that it can cause problems?

**Comment by spco** [comment]
I certainly agree with the first paragraph.

On the second - I think that should be fine too. Is it better to just only allow J-numbers up to the maximum in `photolysisRates.config` (61, with 35 rates in use, so 26 spares left for exactly that use), or go up to, say, `max(100, max in photolysisRates.config file)`? 26 spares currently seems like enough to handle the case you suggest.

**Comment by rs028** [comment]
Probably it should be renamed too, as it is not strictly speaking a config file. Somethign like this?
```
RO2listv3.3.1 -> peroxy.radicals_v3.3.1
photolysisRates.config -> photolysis.parameters_v3.3.1
```

I think 26 spares are  plenty, but if you want you can round it up to 65 or 70.

**Comment by spco** [comment]
Yes, I like the idea of adding the MCM version number like the ro2list file. I think I'll do that in a separate PR, this one's going to be big enough as it is! :)

**Comment by spco** [comment]
#291 fixes most of the issues here

**Comment by rs028** [comment]
@spco Awesome job! Is anything left to do for this issue or can it be closed?

**Comment by spco** [comment]
I think it's just the movement of the MCM files - as we have a PR open for that anyway, I'll close this issue
