### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem2#301]
We should have a `CITATION` or `CITATION.txt` in the main directory, which gives guidance on how to cite AtChem2. e.g https://github.com/swcarpentry/website/blob/gh-pages/CITATION 

This can link to papers and/or to the code itself.

**Comment by rs028** [comment]
Good idea. We just need a paper! Hopefully soon.

**Comment by rs028** [comment]
I have added to PR #303 a (provisional) citation file using the poster submitted for the ACM conference.
