### ISSUE TITLE
Mechanisms in other formats

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem2#304]
The MCM can be downloaded in other formats, besides FACSIMILE:

- KPP format
- XML format (?)

**Comment by xcy12** [comment]
hello，how to add emissions? for example, I want to add vehicle HONO emission in the model. however, HONO emission from the vehicle is thought to occupy 0.3-0.8% if the NOX emission. so I need to add NOX emission to the model.

**Comment by xcy12** [comment]
in addition, I want to add the sedimentation process for some gases. How can I do that?

**Comment by spco** [comment]
Hi @xcy12 - I have opened a new issue for this discussion at #391.

**Comment by xcy12** [comment]
> Hi @xcy12 - I have opened a new issue for this discussion at #391.
It's very nice to have a new issue about this! Thanks a lot! My partners and I will keep on following this issue.
