### ISSUE TITLE
Problems with the fruit library

### ISSUE THREAD

**Issue by mpanagi** [AtChem/AtChem2#364]

**Comment by mpanagi** [comment]
I installed everything compiled the model and run the make tests and all worked. 

When i tried make unittests i get the error below:

make unittests
fruit_generator.rb:4:in `load': cannot load such file -- atchem-libraries/fruit_3.4.3/rake_base.rb (LoadError)
	from fruit_generator.rb:4:in `<main>'
make: *** [travis/unit_tests/fruit_basket_gen.f90] Error 1

Any idea why that is happening?

**Comment by spco** [comment]
Hi @mpanagi. I would initially guess that this file doesn't exist in this location.

1) Does `atchem-libraries/fruit_3.4.3/rake_base.rb` exist? 
2) Which directory are you running `make unittests` from?
3) Is `atchem-libraries` a subdirectory of that directory (or alternatively, just give me the full path to rake_base.rb)

**Comment by spco** [comment]
Hmm. Could you please give me the output of `ruby --version` and `head tools/fruit_generator.rb`? Hopefully that will show up something.

**Comment by mpanagi** [comment]
Below are the outputs you requested:

1. ruby 2.0.0p648 (2015-12-16) [x86_64-linux]


2. [mp558@spectre13 AtChem2-1.1]$ head tools/fruit_generator.rb
require 'rubygems'
require 'fruit_processor'
if ENV['TRAVIS'] == nil
load "fruit_3.4.3/rake_base.rb"
else
  if ENV['TRAVIS_OS_NAME'] == 'linux'
    load "/home/travis/build/AtChem/AtChem2/fruit_3.4.3/rake_base.rb"
  else
    load "/Users/travis/build/AtChem/AtChem2/fruit_3.4.3/rake_base.rb"
  end

**Comment by spco** [comment]
Hmm, the Ruby is a little old, but I'd hope that isn't causing this issue.

In your Makefile, does the line setting `FRUITDIR` point to `fruit-3.4.3`, or to `atchem-libraries/fruit-3.4.3`? I think it needs to be the latter. If so, please do a `make clean`, change `FRUITDIR` to point to `atchem-libraries/fruit-3.4.3`, and then retry `make unittests`.

I'm a little confused, however, as those contents of `tools/fruit_generator.rb` don't seem consistent with the original error...

**Comment by mpanagi** [comment]
The FRUITDIR in the Makefile that i had to copy in the main directory points to atchem-libraries/fruit_3.4.3.

I didn't change anything in the original Makefile that can be found in tools/Makefile

**Comment by spco** [comment]
Hmm. When running `make unittests`,
 https://github.com/AtChem/AtChem2/blob/225ed82102fcd93f83fc0091590c728877361458/tools/Makefile#L84
 should be triggered - this will change line 4 of `$(UNITTESTDIR)/fruit_generator.rb` to `load $(FRUITDIR)/rake_base.rb`. 

That doesn't seem to have happened in your case: `$(FRUITDIR)` in `Makefile` is set to `atchem-libraries/fruit-3.4.3`, but `travis/fruit_generator.rb` contains ` load "fruit_3.4.3/rake_base.rb"`, when it should have changed to ` load "atchem-libraries/fruit_3.4.3/rake_base.rb"`.

That is rather puzzling.

**Comment by spco** [comment]
Apologies about this. I need to have a better look at what's going on. Could you do the following please:
1) `make clean`
2) `make unittests`
3) attach a copy of `travis/unit_tests/fruit_generator.rb` and `Makefile` (from the base directory).

**Comment by spco** [comment]
Actually, before yu do that (if you haven't already started), could ou olease try `make clean` and then change FRUITDIR in your Makefile to use a full path rather than a relative path? So `FRUITDIR=/home/m/mp558/AtChem2-1.1/atchem-libraries/fruit_3.4.3`

**Comment by rs028** [comment]
I will put a note in the wiki to use the full path rather than the relative path.

**Comment by rs028** [comment]
I am reopening this, because I got another error on a different machine.

Also, `rake` must be installed alongside `ruby`? Or it depends on the particular flavor of Linux (this is on a Debian box)?

```
# Running tests:

Finished tests in 0.003636s, 275.0188 tests/s, 275.0188 assertions/s.
1 tests, 1 assertions, 0 failures, 0 errors, 0 skips

ruby -v: ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
generated latest version
  If you have error message "invalid byte sequence UTF-8"
  especially on cygwin before ruby 2.1, try 
    export LANG=""
  before gem install
gem install pkg/fruit_processor-3.4.3.gem
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /var/lib/gems
rake aborted!
Command failed with status (1): [gem install pkg/fruit_processor-3.4.3.gem...]
/home/robertos/atchem-libraries/fruit_3.4.3/fruit_processor_gem/rakefile:72:in `block in <top (required)>'
Tasks: TOP => install
```

**Comment by spco** [comment]
There isn't very much information here - can I close this unless you can give more information?

**Comment by rs028** [comment]
I think we need to clarify what are the exact dependencies needed. Now the manual says ruby, but actually what is needed is rake, which needs ruby.

From my tests:
- ruby 2.0.0 + rake 12.3.1 : OK
- ruby 2.3.3 + rake 10.5.0 : does not install fruit with an error : "you don't have permission to write in /var/lib/gems/2.3.0"

It seems to be related to admin rights. But I am confused because I thought the script `install_fruit.sh` installs a local version of rake (?).

When I run it I get a message:
```
Successfully installed rake-12.3.2
Parsing documentation for rake-12.3.2
Done installing documentation for rake after 1 seconds
1 gem installed
```
and then a `$HOME/bin/rake` executable is created.

**Comment by spco** [comment]
Hmm, we shouldn't really be installing `rake` as a global gem, but rather creating a ruby virtual environment and installing it there. The permissions error is there to force us not to do that. On my Mac it also fails now, but I think that's a fairly new behaviour.

**Comment by rs028** [comment]
The solution is forcing Ruby to install gems locally, as explained here: https://www.michaelehead.com/2016/02/06/installing-gems-without-sudo.html

The latest version of `rake` is installed by `tools/install/install_fruit.sh`, so the only dependency we need to mention for AtChem is Ruby.

This can be closed. I will update the manual/wiki accordingly.
