### ISSUE TITLE
Does photolysisConstant work?

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem2#371]
I tried to test this, but I am not getting the expected result. Maybe I am making a mistake in formatting the `photolysisConstant.config` file?

It looks like this:

    1   1e-3   J1

I am expecting J1 in `photolysis.Rate.output` to be 1e-3 and the others to be zero. But it seems it is calculating all J values.

**Comment by rs028** [comment]
In any case the format seems redundant. It should be enough to do:

    J1 1e-3

in the same manner as the `initialConcentrations.config`

**Comment by spco** [comment]
You're right that it should be setting all others to zero according to https://github.com/AtChem/AtChem2/issues/272#issuecomment-398749169 . Could you explain how you know it's calculating other J values? I'd like to be able to replicate this. I'll have a dig thru the source to check.

On the matter of the formatting, I think you're right, we should be able to recreate one from the other. I'll make a separate issue.

**Comment by spco** [comment]
@rs028 Could you confirm the filename you're using? It should be `photolysisConstant.config` rather than `photolysisConstants.config` - if using the latter then it will be ignored and all rates will be calculated or variably constrained.

**Comment by spco** [comment]
@rs028 - so was this just a misnaming of the file, or does it still not work?

**Comment by rs028** [comment]
The filename is correct.  `photolysisConstant.config` contains 1 line (as per initial comment) and `photolysisConstrained.config` is empty. The model seems to be calculating the photolysis rates.

**Comment by spco** [comment]
I've merged the PR to fix this, but please let me know that it's actually fixed your scenario @rs028
