### ISSUE TITLE
Adding emissions and sedimentation

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem2#391]
hello，how to add emissions? for example, I want to add vehicle HONO emission in the model. however, HONO emission from the vehicle is thought to occupy 0.3-0.8% if the NOX emission. so I need to add NOX emission to the model.

in addition, I want to add the sedimentation process for some gases. How can I do that?

_Originally posted by @xcy12 in https://github.com/AtChem/AtChem2/issues/304#issuecomment-475178049_

**Comment by spco** [comment]
@rs028 - you're the chemist! Could you answer this? I'm happy to pitch in with the specifics if you're able to explain what the above means to a non-chemist?

**Comment by rs028** [comment]
At this stage, the easiest way is to simulate these processes as if they were chemical reactions. The Facsimile format allows to have reactions without products or reactants. For example : 
```
% e : = A ;
```
Where `e` is the emission rate in s-1.

Similarly for deposition:
```
% d : A = ;
```
 Where `d` is the deposition rate. If needed, the boundary layer height is an environment variable which can be used to calculate `d`. For example:
```
% v/BLHEIGHT : A = ;
```
Where `v` is the deposition velocity. 

If you add "reactions" like these at the bottom of the `fac` file, you should be able to parameterize these processes.

**Comment by xcy12** [comment]
That's very great! I will try this method.
Thanks very much for your kind help! @spco @rs028

**Comment by xcy12** [comment]
I have tried this method and it works! Thanks a lot! @spco @rs028
