### ISSUE TITLE
release v1.2

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem2#397]
After merging PR #396 and after the paper has been accepted for publication, a stable version should be released, since major development work is going to stop for a while.

Things to do:

- [x] merge PR #396 
- [x] merge PR #408
- [x] update manual
- [x] update wiki
- [x] update `CITATION.md`
- [x] update `CHANGELOG.md`
- [x] set version number
- [x] merge #424
- [x] recompile pdf of manual
- [x] create new release

**Comment by spco** [comment]
Ok, sounds good. This would include the shared library work from #370, which is quite a step-change in how it is designed.

**Comment by rs028** [comment]
Cool. Did you see my questions in PR #396?

**Comment by spco** [comment]
Er, no, I can't see any there?

**Comment by rs028** [comment]
It is the "review" system. Do you see them now?

**Comment by spco** [comment]
I see them now

**Comment by rs028** [comment]
Closed by #422.
