### ISSUE TITLE
Install problems on CVODE and openlibm

### ISSUE THREAD

**Issue by xcy12** [AtChem/AtChem2#401]
Hello, I'm reading the GMD paper and install AtChem v2.1.1. During the installation, the BLAS and LAPACK are installed by our administrator, not in the default path.  Then how to change the LAPACK_LIBS? Where is this file? For openlibm, it showed Internal conflict.  Thanks very much.

**Comment by spco** [comment]
Hi @xcy12 , is the LAPACK issue during the install of CVODE or AtChem? If it's CVODE then please change the relevant line 26 in `tools/install/install_cvode.sh` to point to the location of LAPACK. Otherwise, you can append $LAPACK_LIBS to $PATH with
```
export $PATH=$PATH:$LAPACK_LIBS
```
where $LAPACK_LIBS is the full path to LAPACK, so that LAPACK is then found.

As for the openlibm issues - could you please supply more information?

If you need more details on either issue, please supply copies of the exact errors you get.

**Comment by xcy12** [comment]
Hello,Thanks very much for your kind help.  I used "export $PATH=$PATH:$LAPACK_LIBS" but it dosen't give me the right result like the "whereis libblas".

LPCE\cxue@gaia:~/AtChem2-1.1.1$ whereis libblas
libblas: /usr/lib/x86_64-linux-gnu/libblas.a /usr/lib/x86_64-linux-gnu/libblas.so
LPCE\cxue@gaia:~/AtChem2-1.1.1$ whereis liblapack
liblapack: /usr/lib/x86_64-linux-gnu/liblapack.a /usr/lib/x86_64-linux-gnu/liblapack.so
LPCE\cxue@gaia:~/AtChem2-1.1.1$ export $PATH=$PATH:$LAPACK_LIBS
-bash: export: « /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: » : identifiant non valable

So, i should modify the line 26 to:

else
  LAPACK_LIBS=/usr/lib/liblapack.so:/usr/lib/libblas.so:/usr/lib/x86_64-linux-gnu/

This will be right? 
Forgive me that i don't know so much about LINUX. Thank you.

**Comment by spco** [comment]
Not a problem. If that's where your BLAS and LAPACK libraries are, then I think you should have 
```
LAPACK_LIBS=/usr/lib/x86_64-linux-gnu/libblas.so:/usr/lib/x86_64-linux-gnu/liblapack.so
```
which should be enough to install CVODE.

**Comment by xcy12** [comment]
thanks a lot. I try it now.

**Comment by xcy12** [comment]
It seems failed.  

mkdir: impossible de créer le répertoire «build»: Le fichier existe
-- The Fortran compiler identification is GNU 7.4.0
-- Searching for a Fortran compiler... /usr/bin/gfortran
-- Trying to compile and link a simple Fortran program... OK
-- Determining Fortran name-mangling scheme... OK
-- Looking for LAPACK libraries... OK
-- Checking if Lapack works... FAILED

**Comment by xcy12** [comment]
Now the path for LAPCK_LIBS in Install_cvode.sh is

if [ "$OS" == 'Darwin' ]; then
  LAPACK_LIBS=/usr/lib/liblapack.dylib:/usr/lib/libblas.dylib
else
  LAPACK_LIBS=/usr/lib/x86_64-linux-gnu/libblas.so:/usr/lib/x86_64-linux-gnu/liblapack.so

**Comment by xcy12** [comment]
I checked the files in  /usr/lib/x86_64-linux-gnu/, there are three liblapack
                                    liblapack.so
                                    liblapack.so.3
                                     liblber-2.4.so.2

**Comment by spco** [comment]
That is how I'd expect your LAPACK_LIBS line to look, yes. Unfortunately, I don't have much insight into the Lapack you have set up on your machine, or on CVODE installation beyond as a user. Are you able to ask your administrator for help with that?

There doesn't look anything wrong with your contents of `/usr/lib/x86_64-linux-gnu/` - one will just point to the other anyway, and `libIber-2.4.so.2` is unrelated.

An alternative is to install Lapack yourself, but that is quite an involved process so I'd not recommend it unless really necessary.

**Comment by xcy12** [comment]
Thanks very much. I agree with you that to install lapack is too complex for me. I will try to discuss with the administrator.

**Comment by xcy12** [comment]
Hi, @spco, I still have another question about GNU gfortran and Intel ifort.   We need both of them or just one is ok? In the word Manual it said "GNU gfortran and Intel ifort", while in the wiki page it said "GNU gfortran or Intel ifort".
2.for lapack, I am going to discuss with the administrator. Maybe re-install it in the  default path. To re-install lapack, do we need to uninstall CVODE and openlibm? Should they be installed in this order: blas-lapack-cvode-openlibm-AtChem2 v1.1.1?

**Comment by spco** [comment]
Hi @xcy12 , you need only one compiler - the phrasing is a bit different in the two places but mean the same thing.

2. That's the general order, yes. The fact that CVODE finds LAPACK but it fails its "working" check means the issue may not be the location, but something with the setup - it's difficult for me to say very much more. I would uninstall CVODE and openlibm beforehand, yes, just to be safe.

**Comment by xcy12** [comment]
@spco OK. I will try to ask the administrator to do this.  Thanks very much. Have a nice day!

**Comment by xcy12** [comment]
Hi, @spco ,  we tried but failed finally.  Still the same problem.
-- Looking for LAPACK libraries... OK
-- Checking if Lapack works... FAILED
While the installation of CVODE was finished. It created the path ~/atchem-libraries/cvode/lib
Our server is new. Our administrator and I discussed this and have some question.
Our configuration is :
- fortran 7
- Ubuntu 18.04.3 LTS
- lapack 3 et bblas 3
+ asking if it'is really grave or not
If these will cause this problem?

**Comment by spco** [comment]
Hmm. This is an issue with the installation of CVODE, so I don't really know what's going on. Are you saying that CVODE installed ok? What are the contents of `~/atchem-libraries/cvode/lib`?

If nothing else, you should be able to install CVODE without LAPACK: simply set the line 80 in `tools/install/install_cvode.sh` to 
```
 -DLAPACK_ENABLE:BOOL=OFF \
```
This won't utilise LAPACK, so may be slower to execute, but I haven't tested to see whether that has any effect or not in reality.

**Comment by xcy12** [comment]
Hi, @spco , I tried to install CVODE with right and wrong path for LAPACK_LIBS in install_cvode.sh, however, they showed the same result:

-- The Fortran compiler identification is GNU 7.4.0
-- Searching for a Fortran compiler... /usr/bin/gfortran
-- Trying to compile and link a simple Fortran program... OK
-- Determining Fortran name-mangling scheme... OK
-- Looking for LAPACK libraries... OK
-- Checking if Lapack works... FAILED
WARNING: LAPACK not functional.
   Blas/Lapack support will not be provided.
-- Added NVECTOR_SERIAL module
-- Added CVODE module
-- Added CVODE FCMIX module
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cxue/atchem-libraries/sundials-2.7.0/build

I wonder how does it look for lapack and find it OK when I gave a wrong path on purpose. 
In the ~cvode/lib/, files are:

libsundials_cvode.a         libsundials_fnvecserial.so.2
libsundials_cvode.so        libsundials_fnvecserial.so.2.7.0
libsundials_cvode.so.2      libsundials_nvecserial.a
libsundials_cvode.so.2.9.0  libsundials_nvecserial.so
libsundials_fcvode.a        libsundials_nvecserial.so.2
libsundials_fnvecserial.a   libsundials_nvecserial.so.2.7.0
libsundials_fnvecserial.so

I agree with you. Maybe it is caused by the installation of CVODE.  Just now I tried  -DLAPACK_ENABLE:BOOL=OFF \
It showed almost the same result, just without

-- Looking for LAPACK libraries... OK
-- Checking if Lapack works... FAILED
WARNING: LAPACK not functional.
   Blas/Lapack support will not be provided.

**Comment by xcy12** [comment]
I find another server with CentOS and all the installation is OK. I'm still trying to find out why the problem occurred on our new server with Ubuntu.

**Comment by rs028** [comment]
Is it maybe a question of which version of blas and lapack are installed on the system? If we need specific versions I can update the manual accordingly.

**Comment by xcy12** [comment]
> Is it maybe a question of which version of blas and lapack are installed on the system? If we need specific versions I can update the manual accordingly.

hi, @rs028  I'm still talking with our network engineer, if we find sth we will let you know.

**Comment by nathimou** [comment]
Hi,
I have installed Atchem and Lapck, and Cvode... on an Ubuntu 64 bits.
To install it, you need to download and install SUNDIALS from the official web site : https://computing.llnl.gov/projects/sundials/download/sundials-4.1.0.tar.gz  . I used the "graphical" installation as root. Be carefull of checking the variable SUNDIALS_INDEX_SIZE  to 32 **before** putting the LAPACK_ENABLE to ON.
After you run the install_cvode.sh as described in the documentation of Atchem2, and the rest of the installation works fine.
I hope this will help you.

**Comment by rs028** [comment]
Closed. This seems to be an issue of Ubuntu, rather than AtChem.
