### ISSUE TITLE
questions about model time

### ISSUE THREAD

**Issue by xcy12** [AtChem/AtChem2#402]
Hi, I 'm calculating JFAC using AtChem2. 
1. Here are the parameters in environmentVariabls.config and model parameters:
EnvironmentVariabls.config
1 TEMP			298.15
2 PRESS			1013.25
3 RH			NOTUSED
5 H2O			3.91e+17
5 DEC			CALC
6 BLHEIGHT		NOTUSED
7 DILUTE		NOTUSED
8 JFAC			NOTUSED
9 ROOF			OPEN
Model.parameters
505			number of steps
3600			step size (seconds)
2			species interpolation method (pw constant = 1, pw linear = 2)
2			conditions interpolation method (pw constant = 1, pw linear = 2)
3600			rates output step size (seconds)
0			model start time (seconds)
0			jacobian output step size (seconds)
38.4			latitude (degrees)
0			longitude (degrees)
03			day
12			month
2017			year
3600			reaction rates output step size (seconds)
the J output is 
![1](https://user-images.githubusercontent.com/47885820/64157059-4ef8e100-ce36-11e9-9043-5a4e435f730d.png)
for longitude=0, UTC time is just the local time.
Then I tried to change longitude to 115.2. the J output is 
![2](https://user-images.githubusercontent.com/47885820/64157179-89fb1480-ce36-11e9-86e1-05698cc9b633.png)
It seems the model is running based on UTC time even you set the lon=115.2.
This means i need to convert local time to UTC time before simulation. 
For atchem-online, it uses the local time. I want to confirm it because the one who uses Atchem-online could easily make a mistake.

**Comment by rs028** [comment]
Yes the model is running on UTC time, but I believe that AtChem-online is also working on UTC. It is not something we changed, is that right @spco?

One thing to note is that the longitude is positive west and negative east, contrary to the normal convention. This is something @mpanagi found some weeks ago and I have been thinking whether we should change it (which would probably be more correct) or keep it this way for backwards compatibility.

**Comment by spco** [comment]
I don't believe that we changed this (I don't know why we would have done?) but I can't find out without a fair amount of detective work!

**Comment by xcy12** [comment]
Hi, @rs028 @spco, I don't agree with you about AtChem-online running on UTC time. Just now i tried two tests with AtChem-online:
1.
![1 1](https://user-images.githubusercontent.com/47885820/64646614-bce56f80-d417-11e9-96d2-225d4ac642f9.png)
![1 2](https://user-images.githubusercontent.com/47885820/64646621-c078f680-d417-11e9-898b-c29a32b11b7c.png)
Note=>  J1 max=0.23E-4, Time:43200s=12:00
2.
![2 1](https://user-images.githubusercontent.com/47885820/64646733-edc5a480-d417-11e9-889f-215b326e285d.png)
![2 2](https://user-images.githubusercontent.com/47885820/64646739-f027fe80-d417-11e9-8014-5085d7134efe.png)
Note=> J1 max=0.23E-4, Time: 43200s=12:00
The two cases showed the same result for Lon=115 or -115. And the model is running on local time not UTC. if it's running on UTC, for Lon=115, the peak J should appear at 4:00, not 12:00. It's local time wiht peak J at 12:00.

**Comment by xcy12** [comment]
I agree with that AtcChem2 runs on UTC time and east longitude has a - value and west longitude has a + value. (Forgive my carelessness that i take east longitude as + values ). And  Then I used AtChem2 to do the same tests just to confirm what you said is exactly right.
1.
![4 1](https://user-images.githubusercontent.com/47885820/64647725-d5568980-d419-11e9-933f-f89a1c219919.png)
![4 2](https://user-images.githubusercontent.com/47885820/64647730-d8517a00-d419-11e9-8820-fe53e85a8f9f.png)
Note=>  J1 max=1.55E-6, Time: 68400s=19:00
2.
![5 1](https://user-images.githubusercontent.com/47885820/64647821-03d46480-d41a-11e9-9c2e-7e59876f5c6f.png)
![5 2](https://user-images.githubusercontent.com/47885820/64647829-0636be80-d41a-11e9-8e18-288f4a057c10.png)
Note=> J1 max=1.61E-6, Time: 14400s=04:00

**Comment by xcy12** [comment]
What I also want to address is about DEC. This value actually largely influences J.  I made test 3 for AtChem online, with the same parameter wiht test 1 except for DEC=CLAC (the previous two use default value 0.287).
![3 1](https://user-images.githubusercontent.com/47885820/64649049-76464400-d41c-11e9-8e58-cef7ac2a5c85.png)
![3 2](https://user-images.githubusercontent.com/47885820/64649052-77777100-d41c-11e9-9397-1f74c0f032d7.png)
Note=>  J1 max=0.21E-5, Time: 43200s=12:00
J1 max reduced a lot with respect to the first test with J1 max 0.23E-4. This DEC value could be important when you don't have measured JNO2 to calculate JFAC.

Thanks very much. Hope I use these models right and understand these results right.

**Comment by spco** [comment]
Hi @xcy12 , I'm not sure which bits you're saying are ok and which are not, but I'm not familiar enough with the chemistry to have much intuition. What I would highlight is that we have certainly changed the way that DEC is calculated: https://github.com/AtChem/AtChem2/blob/d009ac9d36d1556f41d35575734f551950d6b743/constraintFunctions.f#L59 
That's a link to the original commit of AtChem, which is just the source code of Atchem-online. They use a different calculation of DEC than we do here:
https://github.com/AtChem/AtChem2/blob/46fe9d3fb3a68eb8de1eafab10534643d9a354cb/src/solarFunctions.f90#L78
From memory, ours is a more accurate calculation, but I'd have to defer to @rs028 on that. I also have a memory that there was at least one actual bug in the calculation of solar angles (zenith, DEC, etc) which we fixed, but I'm not certain of when or what - it was a while ago!

**Comment by spco** [comment]
The [changelog](https://github.com/AtChem/AtChem2/blob/master/CHANGELOG.md) shows that there were fixes to the solar calculations for both v1.0 and v1.1

**Comment by rs028** [comment]
Yes we did change the way `DEC` is calculated and there were some bugs in AtChem-online which should now be fixed.

We have been doing some tests on the accuracy of `DEC` and `SZA` calculations, which may help clarify the other issues. @mpanagi we should touch base on this.

**Comment by rs028** [comment]
Closing this, as it appears to be solved. More information on the calculation of the solar angles will be posted on the wiki, when the testing is finished.
