### ISSUE TITLE
Improve efficiency of 'implicit none' statements

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem2#407]
So long as a function is within a module, it's sufficient to have a single `implicit none` statement at the top of the module. So we could remove all the many `implicit none`s from the functions, and have only one per module plus one for the main program, and any function that isn't within a module.

Would likely save us a fair few lines (grep finds 122 occurrences, so we'd probably save about 100 lines)

**Comment by rs028** [comment]
Done with PR #424.
