### ISSUE TITLE
Is it because of FRUIT?

### ISSUE THREAD

**Issue by jjunum** [AtChem/AtChem2#421]
I installed AtChem and it seems that the install was OK sicne the test run was completed without error (2.4 Install in user manual).
The make tests runs was ok but not for make alltests and make unittests.
How can I solve this?
Below are the messages I got

$ make unittests
Traceback (most recent call last):
	2: from fruit_generator.rb:15:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- fruit_processor (LoadError)
Makefile:114: recipe for target 'travis/unit_tests/fruit_basket_gen.f90' failed
make: *** [travis/unit_tests/fruit_basket_gen.f90] Error 1

$ make alltests
Running indent script on:
src/argparse.f90
src/atchem2.f90
src/atmosphereFunctions.f90
src/configFunctions.f90
src/constraintFunctions.f90
src/dataStructures.f90
src/inputFunctions.f90
src/interpolationFunctions.f90
src/outputFunctions.f90
src/parameterModules.f90
src/solarFunctions.f90
src/solverFunctions.f90

Indent test PASSED
Indent script finished

Running style script on:
src/argparse.f90
src/atchem2.f90
src/atmosphereFunctions.f90
src/configFunctions.f90
src/constraintFunctions.f90
src/dataStructures.f90
src/inputFunctions.f90
src/interpolationFunctions.f90
src/outputFunctions.f90
src/parameterModules.f90
src/solarFunctions.f90
src/solverFunctions.f90

Style test PASSED
Style script finished

Traceback (most recent call last):
	2: from fruit_generator.rb:15:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- fruit_processor (LoadError)
Makefile:114: recipe for target 'travis/unit_tests/fruit_basket_gen.f90' failed
make: *** [travis/unit_tests/fruit_basket_gen.f90] Error 1

**Comment by rs028** [comment]
Hi @jjunum , which operating system are you using?

**Comment by spco** [comment]
To come back to this, this is usually a sign that Fruit has not correctly installed - you would need to look at the installation step for Fruit to verify whether that gem has installed correctly etc.

I vote we close this issue - it can be reopened if new info is provided, but it's likely an issue with the Ruby gem installation.

**Comment by rs028** [comment]
Ok by me. We can return to it if other people have problems (but in any case the model works even if the unit testing fails).
