### ISSUE TITLE
No convergence when adding dilution rate

### ISSUE THREAD

**Issue by weikou** [AtChem/AtChem2#425]
Hello, 
I downloaded Atchem2  a few days ago and am testing now, how to run a very simple model. The model is running fine, as long as I do not DILUTE my system. If I do that, I run into convergence problems every time. The error occurs always then, when the model should calculate the "reaction rates output step size" for the first time and the error looks as following: 
*******************************************
[CVODE ERROR]  CVode
  At t = 2.04202 and h = 3.8147e-07, the corrector convergence test failed repeatedly or with |h| = hmin.

 ier POST FCVODE()= -4
 time = 2

 SUNDIALS_ERROR: FCVODE() returned ier =    -4
Linear Solver returned ier =     2
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_DIVIDE_BY_ZERO IEEE_OVERFLOW_FLAG
*******************************************
I already tried to play around with solver step size and atol / rtol, but it's not leading anywhere. 
Do you have any suggestions what I could try to look into to solve this?

**Comment by rs028** [comment]
@weikou This is most likely a numerical issue. Have you tried changing the value of `DILUTE`? Do you have rapidly changing conditions in your model?

**Comment by weikou** [comment]
I now found the issue and it was not directly related to something numeric. The filepath to the mechanism.so wasn't updated. It was unclear to me, from chapter 4.4 in the doc, that I would need to manually set the shared_lib path, while all others were set automatically to the correct folder, when I wrote --model=path/to/my/model
Maybe this could be clarified in the doc or adjusted in the code, so that it behaves as the other arguments.
So, actually it was a stupid error from my side, I am still learning. It is running fine now :) Thank you!

**Comment by rs028** [comment]
Great! This problem is related to issue #414, but I will make a note to clarify the manual. BTW, the latest version of the model (v1.2) was released only a few days ago and has a much improved manual.  I suggest you update if you haven't already.
