### ISSUE TITLE
Build_Atchem2.sh - make sharedlib issue

### ISSUE THREAD

**Issue by baongocthai** [AtChem/AtChem2#434]
Hi all,

When I tried to run the Build_Atchem2.sh using the following command:
./build_atchem2.sh mcm/mechanism_test.fac model/configuration/ mcm/ 

The following log appears:
_* facsimile mechanism file: mcm/mechanism_test.fac
* fortran mechanism directory [ default = ./model/configuration/ ]: model/configuration/
* mcm data files directory [ default = ./mcm/ ]: mcm/

call mech_converter.py
/home/nus/Documents/Atchem2/AtChem2-1.2/mcm
Running fix_fac_file on /home/nus/Documents/Atchem2/AtChem2-1.2/mcm/mechanism_test.fac
/home/nus/Documents/Atchem2/AtChem2-1.2/mcm/mechanism_test.fac: file read in 255 items
0 corrections made - now removing old
Reading input file
looping over inputted RO2s
adding RO2 to model/configuration//mechanism.ro2

make sharedlib model/configuration/
make: *** No rule to make target 'sharedlib'.  Stop._

Could you advise on how to solve the problem with sharedlib?

Thanks!

**Comment by rs028** [comment]
@baongocthai are you running the `build_atchem2.sh` script from the main directory or from the `build/` directory?

**Comment by baongocthai** [comment]
Hi @rs028 , thanks for the guide!! I managed to resolved the problem by looking at your response!

**Comment by morshedahmed17** [comment]
Hi all,

When I tried to run the Build_Atchem2.sh using the following command:
./build/build_atchem2.sh model_1/mechanism_test.fac model_1/configuration/ mcm/


* facsimile mechanism file: model_1/mechanism_test.fac

* fortran mechanism directory [ default = ./model/configuration/ ]: model_1/configuration/

* mcm data files directory [ default = ./mcm/ ]: mcm/



call mech_converter.py

/Users/tanzinaakther/Desktop/AtChem2/model_1

Running fix_fac_file on /Users/tanzinaakther/Desktop/AtChem2/model_1/mechanism_test.fac

/Users/tanzinaakther/Desktop/AtChem2/model_1/mechanism_test.fac: file read in 255 items

0 corrections made - now removing old

Reading input file

looping over inputted RO2s

adding RO2 to model_1/configuration//mechanism.ro2



make sharedlib model_1/configuration/

make: *** No rule to make target `sharedlib'.  Stop.


Not sure how to solve this. It's a similar problem like @baongocthai.

**Comment by rs028** [comment]
Hi @morshedahmed17, the problem of @baongocthai was launching the build script from within the `build/` directory, instead of the main directory. Is this is your case?

**Comment by morshedahmed17** [comment]
I am running it from the source directory. 

./build/build_atchem2.sh model_1/mechanism_test.fac model_1/configuration/ mcm/

Getting the same error message. Please see the attached image also. 

![AtChem2](https://user-images.githubusercontent.com/90218942/144295431-ec3ffc99-66e6-4048-b880-7239cec45807.jpg)

**Comment by rs028** [comment]
Are you able to compile the test mechanism and run the tests? See the manual at the end of the installation section,

**Comment by morshedahmed17** [comment]
Hello, 

I ran the test code but still got the same error message. Please see the attached screenshot. 
<img width="1412" alt="Screen Shot 2021-12-06 at 5 00 57 PM" src="https://user-images.githubusercontent.com/90218942/144936881-201d9891-b50b-48d1-b4be-160146a4bd65.png">

**Comment by rs028** [comment]
I would say that something is wrong with your dependencies or the paths. Can you try to reinstall everything, maybe on a different machine if possible?

**Comment by rs028** [comment]
@morshedahmed17 did you solve the problem? Have you tried the development version (https://github.com/AtChem/AtChem2/archive/refs/heads/master.zip) instead of one of the releases?

**Comment by morshedahmed17** [comment]
I have solved the problem. I tried with my university cluster and it worked. Thanks
