### ISSUE TITLE
Move Travis to GitHub Actions

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem2#439]
Travis is essentially shutting down for free projects, but GitHub has its own GitHub Actions that cover the same functionality. It should be reasonably easy to port across to use Actions - they're very similar, and there are guides to convert.

Adding this here as a note to do that soon to get CI back up and running.

Limited to 500MB, and 2000 minutes/month (with macOS builds being charged at 10 times the rate so 1 minute on macOS counts as 10 towards the total) but that should cover our current usage very easily.

**Comment by rs028** [comment]
The new system should test at least a couple versions of each compiler (see also issue #398).
If this takes too much time, we can consider a setup where only one compiler is tested during a PR, but then more than one is tested when triggering the merge into `master`.

**Comment by spco** [comment]
Closed by #441, #443 and #444
