### ISSUE TITLE
Species concentrations at output are too high

### ISSUE THREAD

**Issue by motimace** [AtChem/AtChem2#449]
Hello,

when I ran model based on initial ozone concentrations and constrained environmental variables & species concentrations, 

1. the simulated concentrations of ozone are  significantly higher than observed values.
2.  the trend of simulated and observed concentrations is inconsistent..
![mmexport1617350583020.png](https://user-images.githubusercontent.com/35254916/113395757-ed5f7680-93cc-11eb-8fe3-80e49e4da80b.png)

How do I solve this problem?

Thank you.

**Comment by rs028** [comment]
Hi @motimace this does not look like a problem with the model. AtChem2 (and the MCM) is a research tool and I would not expect it to be always be able to reproduce all the observations. Especially in the case of ozone which is affected by a number of physical and meteorological processes, besides the chemistry. You should probably consider what you are trying to model and how, and what your objective is. Hope this helps.

**Comment by Moonshadow-bc** [comment]
Have you solved the problem? I also had such a situation when simulating ozone concentration (usually in the simulation time of about three days), what caused such a problem? thank you.
