### ISSUE TITLE
photolysis rate calculation (lat/lon specification)

### ISSUE THREAD

**Issue by mpperezp** [AtChem/AtChem2#452]
Hi, I have been running several simulations with AtChem2v1.2 and have come across a weird issue when setting the latitude and longitude to 4.98 and 117.8 respectively, the model seems to estimate photolysis rates for nighttime hours. This is how my model.parameters looks:

135                     number of steps
3600                    step size (seconds)
2                       species interpolation method (pw constant = 1, pw linear = 2)
2                       conditions interpolation method (pw constant = 1, pw linear = 2)
3600                    rates output step size, ROPA/RODA (seconds)
64800                   model start time (seconds)
0                       jacobian output step size (seconds)
4.98                    latitude (degrees)
117.8                   longitude (degrees)
11                      day
7                       month
2008                    year
3600                    reaction rates output step size (seconds)

I have 14 constrained species and TEMP and RH constrained as well. As you see, the model is set to start at 7:00pm (first time available in my constraints), but the photolysis rate output looks like this (I have added the hour column for clarity):

hour | t | J1
7:00:00 PM | 6.84E+04 | 3.14E-05
8:00:00 PM | 7.20E+04 | 3.36E-05
9:00:00 PM | 7.56E+04 | 3.09E-05
10:00:00 PM | 7.92E+04 | 2.40E-05
11:00:00 PM | 8.28E+04 | 1.49E-05
12:00:00 AM | 8.64E+04 | 6.27E-06
1:00:00 AM | 9.00E+04 | 9.13E-07
2:00:00 AM | 9.36E+04 | 1.14E-18
3:00:00 AM | 9.72E+04 | 0.00E+00
4:00:00 AM | 1.01E+05 | 0.00E+00
5:00:00 AM | 1.04E+05 | 0.00E+00
6:00:00 AM | 1.08E+05 | 0.00E+00
7:00:00 AM | 1.12E+05 | 0.00E+00
8:00:00 AM | 1.15E+05 | 0.00E+00
9:00:00 AM | 1.19E+05 | 0.00E+00 (...)

Now, I wanted to test further keeping the same constraints and changing only the lat and Lon to 0.0, 0.0 the model seems to respond correctly giving the following

hour | t | J1
7:00:00 PM | 6.84E+04 | 0.00E+00
8:00:00 PM | 7.20E+04 | 0.00E+00
9:00:00 PM | 7.56E+04 | 0.00E+00
10:00:00 PM | 7.92E+04 | 0.00E+00
11:00:00 PM | 8.28E+04 | 0.00E+00
12:00:00 AM | 8.64E+04 | 0.00E+00
1:00:00 AM | 9.00E+04 | 0.00E+00
2:00:00 AM | 9.36E+04 | 0.00E+00
3:00:00 AM | 9.72E+04 | 0.00E+00
4:00:00 AM | 1.01E+05 | 0.00E+00
5:00:00 AM | 1.04E+05 | 0.00E+00
6:00:00 AM | 1.08E+05 | 0.00E+00
7:00:00 AM | 1.12E+05 | 4.70E-07
8:00:00 AM | 1.15E+05 | 4.93E-06
9:00:00 AM | 1.19E+05 | 1.29E-05 (...)

Other simulations that I've done (with other set of constraints and start times) perform as expected with lat and lons of (16.82, -24.89) and (51.32, -6.5), the problem seems to be with this location that I am testing.

Thank you for your help.

**Comment by spco** [comment]
Hi @mpperezp the time should be given in UTC ("day and month and year" on p21 of the manual). So I think this will account for the photolysis rate output you see. @rs028 perhaps we could update the "model start time" section on that page of the manual to make it more clear that the time is UTC, not local to the longitude?

**Comment by rs028** [comment]
Yes, will do. This is an important point of the model settings and should be very clear to the user.
