### ISSUE TITLE
productionRates.output and lossRates.output 

### ISSUE THREAD

**Issue by 1kyne-256** [AtChem/AtChem2#461]
What are the units of the rate variable in the productionRates.output and lossRates.output  files? 
How is productionRates and  lossRates calculated? What's the formula for the rate of formation?
For example, what about the productionRate of O3  and the lossRates of O3 consumption?
![图片1](https://user-images.githubusercontent.com/64003532/141946589-aeaa85ec-cecd-459e-84d7-a756bae38cd1.png)

**Comment by rs028** [comment]
Hi @1kyne-256 the model works in `molecule cm-3` (concentrations) and `seconds` (time). The units of the reaction rates are calculated accordingly.

`productionRates` and `lossRates` are simply the reaction rates of each reaction that forms and consumes a given molecule. The values should be the same as those in the `reactionRates/` directory, only in a more user-friendly format for selected species of interest. Hope this helps.

**Comment by 1kyne-256** [comment]
> Thank you very much .
There's another problem.
If I wanted to calculate the net photochemical production rate of ozone, what data would I use to calculate it(PO3)?

The calculation formula is as follows:
Photochemical reaction is the dominant source of near-surface ozone, and its process can be represented by (R1)~(R3) :
![image](https://user-images.githubusercontent.com/64003532/142967805-21c4173d-8346-45bb-9440-f30df7a1087b.png)
During the whole process, peroxic radicals (HO2 and RO2) oxidize NO to produce NO2(φ describes the yield of NO oxidized by RO2 to produce NO2, and its value is less than 1), which then photolyzes to produce O3.
The total photochemical generation rate of ozone can be expressed as:
![image](https://user-images.githubusercontent.com/64003532/142967975-4da7dc7d-00ac-4664-9afe-6c187483d570.png)
At the same time, ozone can also be removed by some photochemical reactions, such as (R4)~(R8):
![image](https://user-images.githubusercontent.com/64003532/142968011-12cb7835-dab2-46e7-933f-fe3b3c3d8268.png)
The photochemical removal rate of ozone can be expressed as:
![image](https://user-images.githubusercontent.com/64003532/142968057-538dd26c-3c84-4380-b54c-10d398aa7837.png)
The net photochemical production rate of ozone (P(O3)) is the difference between G(O3) and D(O3).
![1637638781(1)](https://user-images.githubusercontent.com/64003532/142968102-d737a6b5-0a3a-4e5e-813c-fe08626b0b0e.png)

**Comment by 1kyne-256** [comment]
Thank you very much .
There's another problem.
If I wanted to calculate the net photochemical production rate of ozone, what data would I use to calculate it(PO3)?

The calculation formula is as follows:
Photochemical reaction is the dominant source of near-surface ozone, and its process can be represented by (R1)-(R3) :
![image](https://user-images.githubusercontent.com/64003532/142968496-a141d2f3-3fcf-4212-b972-cb3188dcb2d5.png)
During the whole process, peroxic radicals (HO2 and RO2) oxidize NO to produce NO2(φ describes the yield of NO oxidized by RO2 to produce NO2, and its value is less than 1), which then photolyzes to produce O3.
The total photochemical generation rate of ozone can be expressed as:
![image](https://user-images.githubusercontent.com/64003532/142969036-c8f5f709-34e6-4dfb-8aa8-5e09b35df29b.png)
At the same time, ozone can also be removed by some photochemical reactions, such as (R4)-(R8):

**Comment by 1kyne-256** [comment]
Thank you very much .
There's another problem.
If I wanted to calculate the net photochemical production rate of ozone, what data would I use to calculate it(PO3)?
The calculation formula is as follows:
Photochemical reaction is the dominant source of near-surface ozone, and its process can be represented by (R1)-(R3) :
![image](https://user-images.githubusercontent.com/64003532/142977084-21ffc133-71e5-4bf9-855d-93f4379472ed.png)
During the whole process, peroxic radicals (HO2 and RO2) oxidize NO to produce NO2(φ describes the yield of NO oxidized by RO2 to produce NO2, and its value is less than 1), which then photolyzes to produce O3.
The total photochemical generation rate of ozone can be expressed as:
![image](https://user-images.githubusercontent.com/64003532/142977129-05f3ec53-432a-4214-a70e-2cd158263352.png)
At the same time, ozone can also be removed by some photochemical reactions, such as (R4)-(R8):
![image](https://user-images.githubusercontent.com/64003532/142977176-14061959-033d-4861-8f48-461e29d0a407.png)
The photochemical removal rate of ozone can be expressed as:
![image](https://user-images.githubusercontent.com/64003532/142977198-15e3911e-9a5b-4ae5-8f80-94ced11efbb6.png)
The net photochemical production rate of ozone (P(O3)) is the difference between G(O3) and D(O3).
![1637647021(1)](https://user-images.githubusercontent.com/64003532/142977250-6c170d0f-d253-4ad0-8556-e7164be71510.png)

**Comment by rs028** [comment]
@1kyne-256 you can set up the model to output the production and loss rates of OH, HO2, O1D, O3, NO and the reaction rates will be the terms in your G(O3) and D(O3). It will take quite a bit of processing of the output files I am afraid.
Also be careful that the model must NOT be constrained to O3 and/or NO otherwise the results won't make sense.

**Comment by 1kyne-256** [comment]
@rs028 Thank you very much .
So that means that the output of O3 production rates is not G (O3),  and the output of O3 loss rates is not D (O3).
I have to do a lot of processing to get to my final goal, right?
At one time, I thought, all I had to do was set the productivity and loss rate for O3, and then I could calculate P (O3).Now it seems that I misunderstood.

**Comment by rs028** [comment]
That's correct: `productionRates` and `lossRates` will give you the reaction rates of each individual reaction that forms and destroys the selected species, not their sum.
