### ISSUE TITLE
Error with test suite

### ISSUE THREAD

**Issue by Jkhadgi** [AtChem/AtChem2#463]
Error while running make test:
![image](https://user-images.githubusercontent.com/84034928/147318942-61197d0c-7bfa-4737-ada2-38bb5fd436a1.png)

**Comment by rs028** [comment]
Looks like you did not install `numdiff`. See section 2.3.2 of the manual.

**Comment by spco** [comment]
Hi @Jkhadgi . Please ignore the libgcov errors, as they're an artefact of the code coverage system, and can be safely ignored in this instance :)

**Comment by Jkhadgi** [comment]
@spco thanks!!
