### ISSUE TITLE
Compiling Error from MCM Website Extract Tool When Looping over Inputted RO2s

### ISSUE THREAD

**Issue by bethechange** [AtChem/AtChem2#471]
Hi, when I use your MCM Website extract tool with various subsets (I tried this with the complete set; C1/C2/C3/benzene/toluene; C1/benzene) I get the following error. Thanks for either helping me pinpoint what I'm doing wrong or looking into this!
-s

![image](https://user-images.githubusercontent.com/4286519/163735568-7d6bbbeb-20d9-47cd-b08e-c2bbbda638a8.png)

**Comment by spco** [comment]
Hi, it _looks_ like this may be a matter of the order of lines in your MCM file.

To explain, each chemical species must be first introduced on the left-hand side (LHS) of a line in the .fac file, _before_ it is ever used on the right-hand side (RHS) of one. So it looks like you may use `NO` on the RHS of a line without having previously used it on the LHS of another line. Can you confirm whether this is the case? If not, perhaps you'd be kind enough to send me your .fac file here?

If I've correctly diagnosed your case, then you should be able to fix it by reordering some of your lines.

**Comment by rs028** [comment]
@bethechange did you check the options ` Include inorganic reactions?` and ` Include generic rate coefficients?`  when you downloaded the subset from the MCM website?

**Comment by bethechange** [comment]
Yes :)

**Comment by rs028** [comment]
Hi @bethechange can you have a look at the discussion on #451 and #470 for a solution to this problem.

**Comment by bethechange** [comment]
Thanks! Commenting out the excess reactions worked:

# KNO = KRO2NO*NO ;
# KHO2 = KRO2HO2*HO2*0.706 ;
# KRO2 = 1.26D-12*RO2 ;
# KNO3 = KRO2NO3*NO3 ;
# KTR = KNO + KHO2 + KRO2 + KNO3 ;
# K16ISOM = (KTR*5.18D-04*EXP(1308/TEMP)) +(2.76D07*EXP(-6759/TEMP)) ;
