### ISSUE TITLE
How to add photolysis frequency 

### ISSUE THREAD

**Issue by morshedahmed17** [AtChem/AtChem2#472]
Hello, 

I need to add the photolysis frequency of some nitrophenol compounds which are not included in the MCM. And I am not sure how and where in the mechanism file to add that. Can you please help me with that?

**Comment by morshedahmed17** [comment]
Hello @rs028, 
Thanks for your email. I think I understand what you said but not sure how to execute it. I am providing you with an example. 
"The photolysis of NP (and other nitrated phenols) is not included in the MCM v3.2. We added the photolysis frequency of NP (1.4% of photolysis frequency of NO2) into the MCM v3.2." (Yuan et al., 2016)
Can you please let me know exactly where (photolysisConstant.config?) and what format should I write to add the above photolysis frequency? 
Note: My photolysisConstant.Config and photolysisConstrained.config files are empty.

**Comment by rs028** [comment]
@morshedahmed17 If I understand correctly what you are trying to do, the easiest implementation would be something like this.
In the mechanism file (the `.fac` file):
```
% J<4>*0.014  :  NP = A + B ;
```
where A and B are the products of NP's photolysis.

The files `photolysisConstant.config` and `photolysisConstrained.config` should remain empty if your photolysis rates are calculated. You need them only if your photolysis rates are constant or constrained to measured values, respectively.
See section 3.5 of the manual and figure 3.1 to understand how this works.

**Comment by morshedahmed17** [comment]
@rs028 Thanks for your reply. It worked. 

Currently, I am stuck on a different issue. How can I add physical loss rate data to AtChem2?

**Comment by rs028** [comment]
The easiest way would be to represent them as "chemical reactions". See the manual section 3.1.1 for a quick explanation.

**Comment by morshedahmed17** [comment]
@rs028 the issue is solved. However, I recently encountered another issue related to the photolysis frequency of J(NO2). I want to constrain the measured J(NO2). During the night the J(NO2) values are zero but the model does not accept zero values. Any idea how to resolve this issue?

**Comment by rs028** [comment]
Great, then I am going to close this issue.

The easiest way for this new problem is to set the nocturnal values in the constraint file to a very small number, such as 1e-100 or something like that. I would then check the output of J4 (in `photolysisRates.output`) to make sure that it is okay.
