### ISSUE TITLE
Emission of species 

### ISSUE THREAD

**Issue by morshedahmed17** [AtChem/AtChem2#484]
Hello, 
I was trying to add the emission (Er) of species P1 using the following command in the mechanism file.  
% Er : = P1 ;
However, no change is observed in the species concentration. Any idea?

**Comment by morshedahmed17** [comment]
Hello, 
The emission rate is working on my end now. I had some issues with my university cluster and I was not getting output update which is resolved now. You can close this issue.

**Comment by morshedahmed17** [comment]
Hello, 
The unit of emission rate "Er" is reciprocal seconds (s-1) according to the paper "AtChem (version 1), an open-source box model for the Master Chemical Mechanism". However, the emission rate unit is in a format of mass/time. Do you have any idea why it is only s-1 in the paper?

**Comment by rs028** [comment]
@morshedahmed17 the emission rate coefficient is in 1/time, the emission rate  is in mass/time. Hope it makes sense.

**Comment by morshedahmed17** [comment]
@rs028 In the paper it says "emission rate" not "emission rate coefficient". And what is the physical meaning of the term emission rate coefficient?

**Comment by rs028** [comment]
@morshedahmed17 in AtChem, processes like emissions and deposition are represented as "chemical reactions". It is simply a shortcut to write a differential equation that the program already knows how to pass to the solver. See Section 3.1.1 in the Manual for details.

**Comment by morshedahmed17** [comment]
@rs028 is it possible to use constrained emission data?

**Comment by rs028** [comment]
@morshedahmed17 do you mean constrain the emission rate or the concentration?

**Comment by morshedahmed17** [comment]
@rs028 yes, constrain emission rate.

**Comment by rs028** [comment]
The model is not currently set up to do that. In theory it is possible.  For example, the photolysis rates can be constrained.
You would need to modify the code to define a new variable and to allow this variable to be constrained. I did something similar when I added the Aerosol Surface Area to the model (see #473 and #432 for information).
