### ISSUE TITLE
Reducing any concentration of VOCs yields the same O3 concentration.

### ISSUE THREAD

**Issue by 11aurora1** [AtChem/AtChem2#492]
Hello, I found that when using the AtChem2 model to do precursor emissions scenarios for drawing EKMA curves, the simulated O3 concentrations of the model with no reduction in VOCs concentration and those with 50% and 90% reductions are basically the same, and even higher than that of the model with no reduction. I think that the O3 concentration should decrease after reducing VOCs by 50% and 90%. Do you know why this is happening? (Note: O3 is not constrained, while VOCs, NOx, SO2, CO, temperature, humidity, and air pressure are constrained.)
[Data.pdf](https://github.com/AtChem/AtChem2/files/11291647/Data.pdf)

**Comment by rs028** [comment]
I am closing this issue, as it not really about the model functionality, but usage and interpretation of the results.

**Comment by MarchettiJ** [comment]
I also encountered this problem, but I don't know how to deal with it, and I haven't found any relevant tutorials yet.

**Comment by MarchettiJ** [comment]
> I also encountered this problem, but I don't know how to deal with it, and I haven't found any relevant tutorials yet.

or i think atchem2 should not be used to draw EKMA.
