### ISSUE TITLE
gfortran-9 removed from macos-11 runner image, causing a failing test

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem2#493]
`gfortran-9` was recently removed from the macos-11 runner image, see https://github.com/actions/runner-images/commit/3c5dc9d3a7d0a9b562464587ff9e243ca3094801 for the change.

We handle this in macos-12 (which lacks gfortran-9) in the `ci.yml` stage "Install gfortran-9 or gfortran-10 on macOS-12 if required".

The simple fix to this would be to add another condition to that stage, so it also runs when `matrix.os == 'macos-11' && matrix.fortran == 9`

**Comment by spco** [comment]
We should also rename that stage (or perhaps add another, separate one that handles the macos-11 case?) to ensure clarity is maintained.

**Comment by rs028** [comment]
@spco This is solved between PR #482 and #496 right?
At the moment, gfortran 9, 10 and 11 are implemented for both versions of macos, although 9 is provisionally disabled on macos-12.
