### ISSUE TITLE
CVODE ERROR

### ISSUE THREAD

**Issue by zyh9291** [AtChem/AtChem2#498]
Hello, 
In a recent simulation, I only changed the species' concentrations with leaving the rest of parameter settings unchanged, but it reported a running error that was 
" [CVODE ERROR]  CVode
  At t = 61200 and h = 2.36018e-13, the corrector convergence test failed repeatedly or with |h| = hmin.
 SUNDIALS_ERROR: FCVODE() returned ier =    -4
Linear Solver returned ier =     2"
I’m not sure if it's because of the data. I was wondering if there are some methods to solve this problem.
Thank you for your attention to this matter. I would appreciate any help you can offer.

**Comment by rs028** [comment]
Hi @zyh9291 I assume you are talking about the initial concentration. If you change back to the value that you had before do you still get the same error?

**Comment by zyh9291** [comment]
Hello @rs028 There was a 'CVODE ERROR' after changing the constraint concentration, but it was possible to run successfully with the previous value.

**Comment by rs028** [comment]
In this case I think it strongly suggests that the new value you are using is creating the problem. Which variable is it and what are the values (old and new)?

**Comment by zyh9291** [comment]
I changed the constraint concentrations for 72 species(VOCs, NOx, CO...). May I take it that this set of constrained datas cannot be solved by CVODE?

**Comment by zyh9291** [comment]
@rs028 Thanks for your advice and assistance.
