### ISSUE TITLE
Build function is not working

### ISSUE THREAD

**Issue by tanzinaakther** [AtChem/AtChem2#499]
Hi, I was running the model fine. But suddenly, I am facing this issue although I ran the model with the same code just 2 days ago and it was working properly.
You can see, in the left, where my files directory exactly matches with the code, but it gives assertion error and says failed to find files.
<img width="960" alt="Model run pblm" src="https://github.com/AtChem/AtChem2/assets/123010272/2cccda09-6b98-472e-9fbb-dd433e392c05">

**Comment by rs028** [comment]
Hi @tanzinaakther this may be a stupid question, but ... is the `mechanism.fac` file in the `model_rns` directory?

**Comment by tanzinaakther** [comment]
Yes , mechanism.fac file is there.

**Comment by tanzinaakther** [comment]
<img width="269" alt="Capture" src="https://github.com/AtChem/AtChem2/assets/123010272/2dfbf430-8e0f-4189-b88c-8b33693176bc">
See this

**Comment by rs028** [comment]
I am not sure what to suggest. If it was working before and if you haven't changed anything in the setup or the code, then I see no reason why it should not work now. The only suggestion I have (not particularly helpful I realize) is to check carefully that all commands, files, directories and paths are correct and are where they are supposed to be, and to review any changes you may have made.

**Comment by rs028** [comment]
I am closing this, please reopen it if it is still an issue.
