### ISSUE TITLE
CVODE WARNING t + h = t

### ISSUE THREAD

**Issue by lcsmmn** [AtChem/AtChem2#508]
Hey, in a simulation i get the warning:

```
[CVODE WARNING]  CVode
"Internal t = 38259.2 and h = 3.06996e-12 are such that t + h = t on the next step. The solver will continue anyway.

[CVODE WARNING]  CVode
  The above warning has been issued mxhnil times and will not be issued again for this problem."
```

I start my model at 36000 seconds. The problem stops when i take out some constraints but constraints that don't work are not much different from the ones that do, any ideas?

**Comment by rs028** [comment]
HI @lcsmmn did the model complete its run and just printed out a warning, or did it crash before the end?

**Comment by lcsmmn** [comment]
It's stuck in the warning, no error or crash.

**Comment by rs028** [comment]
It looks like a numerical issue, i.e. the system produces numbers that the solver struggles to deal with. You can try to play with the solver.parameters file, or look carefully at the input data (including the constraints) to see which one in particular is causing the problem. Hope this helps.

**Comment by liuxiaoyu4545** [comment]
Hello, I also encountered a similar problem. When I added the O3 to the constraints file, this problem occurred. How did you correct the error in the constraints file? I have tried to replace the ozone data and extend the data, but they have not been resolved. I hope to receive your reply. Thanks!

**Comment by liuxiaoyu4545** [comment]
> Thanks, it was a error in the constraints file.

Hello, I also encountered a similar problem. When I added the O3 to the constraints file, this problem occurred. How did you correct the error in the constraints file? I have tried to replace the ozone data and extend the data, but they have not been resolved. I hope to receive your reply. Thanks!

**Comment by rs028** [comment]
@liuxiaoyu4545, see my comment above for possible approaches to solve the problem. The timestamp of the warning may give clues as to which section of your constraints dataset is creating the issue.

**Comment by lcsmmn** [comment]
I was editing my files on Windows, then running AtChem in a Linux VM, my problem got solved when i started editing my files also in linux.

**Comment by liuxiaoyu4545** [comment]
> @liuxiaoyu4545, see my comment above for possible approaches to solve the problem. The timestamp of the warning may give clues as to which section of your constraints dataset is creating the issue.
Thank you for your answer. Before the "model run" appeared, the previous information displayed some warnings,as shown in the figure. Does this have any impact on the subsequent operation?
![1](https://github.com/AtChem/AtChem2/assets/152474372/181691d7-9912-4455-bab6-843f36944bc5)


![2](https://github.com/AtChem/AtChem2/assets/152474372/d5efd730-6a05-4c6f-b058-e9fece664b2c)

**Comment by liuxiaoyu4545** [comment]
> I was editing my files on Windows, then running AtChem in a Linux VM, my problem got solved when i started editing my files also in linux.



> I was editing my files on Windows, then running AtChem in a Linux VM, my problem got solved when i started editing my files also in linux.

Thank you for your reply. My constraint files were processed and edited in the Linux system. Unfortunately, there are still previous issues, which may be related to the solver.

**Comment by spco** [comment]
Hi @liuxiaoyu4545 the `ifort warning` you show in those screenshots is not a problem - you can safely ignore that warning.

**Comment by liuxiaoyu4545** [comment]
> Hi @liuxiaoyu4545 the `ifort warning` you show in those screenshots is not a problem - you can safely ignore that warning.
Okay, I understand. Thank you very much!
